version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - sentiment-api-1
      - sentiment-api-2
      - sentiment-api-3
    restart: unless-stopped

  sentiment-api-1:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    expose:
      - "8000"
    volumes:
      - ../models/saved/sentiment_model:/app/models/saved/sentiment_model:ro
      - ../models/saved/sentiment_tokenizer:/app/models/saved/sentiment_tokenizer:ro
      - ../scripts/model_serving/logs:/app/logs
      - ../scripts/model_serving/static:/app/static
      - ../scripts:/app/scripts:ro
    environment:
      - MODEL_PATH=/app/models/saved/sentiment_model
      - TOKENIZER_PATH=/app/models/saved/sentiment_tokenizer
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - INSTANCE_ID=1
      - PYTHONPATH=/app
      - TEST_MODE=false
      - SKIP_MODEL_LOAD=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sentiment-api-2:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    expose:
      - "8000"
    volumes:
      - ../models/saved/sentiment_model:/app/models/saved/sentiment_model:ro
      - ../models/saved/sentiment_tokenizer:/app/models/saved/sentiment_tokenizer:ro
      - ../scripts/model_serving/logs:/app/logs
      - ../scripts/model_serving/static:/app/static
      - ../scripts:/app/scripts:ro
    environment:
      - MODEL_PATH=/app/models/saved/sentiment_model
      - TOKENIZER_PATH=/app/models/saved/sentiment_tokenizer
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - INSTANCE_ID=2
      - PYTHONPATH=/app
      - TEST_MODE=false
      - SKIP_MODEL_LOAD=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  sentiment-api-3:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    expose:
      - "8000"
    volumes:
      - ../models/saved/sentiment_model:/app/models/saved/sentiment_model:ro
      - ../models/saved/sentiment_tokenizer:/app/models/saved/sentiment_tokenizer:ro
      - ../scripts/model_serving/logs:/app/logs
      - ../scripts/model_serving/static:/app/static
      - ../scripts:/app/scripts:ro
    environment:
      - MODEL_PATH=/app/models/saved/sentiment_model
      - TOKENIZER_PATH=/app/models/saved/sentiment_tokenizer
      - LOG_LEVEL=INFO
      - LOG_DIR=/app/logs
      - INSTANCE_ID=3
      - PYTHONPATH=/app
      - TEST_MODE=false
      - SKIP_MODEL_LOAD=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 