version: '3'

services:
  sentiment-api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../models/saved:/project/models/saved
    environment:
      - MODEL_PATH=/project/models/saved/sentiment_model
      - TOKENIZER_PATH=/project/models/saved/sentiment_tokenizer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3 