channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=24.0
- pip:
  - mlflow==2.22.0
  - accelerate==1.5.2
  - backports-functools-lru-cache==1.6.4
  - backports-tempfile==1.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.6
  - gmpy2==2.1.2
  - jaraco-classes==3.2.1
  - jaraco-collections==5.1.0
  - jinja2==3.1.2
  - lz4==4.3.2
  - numpy==1.24.3
  - pandas==2.2.3
  - pathlib==1.0.1
  - scikit-learn==1.3.0
  - scipy==1.10.1
  - tblib==1.7.0
  - tf-keras==2.19.0
  - torch==2.3.0
  - torchvision==0.18.1a0
  - transformers==4.50.3
name: mlflow-env
