name: CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: sentiment-analysis
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Create model directories
      run: |
        mkdir -p models/saved/sentiment_model
        mkdir -p models/saved/sentiment_tokenizer
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployment/Dockerfile
        push: true
        platforms: linux/amd64,linux/arm64/v8
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        build-args: |
          BUILDKIT_INLINE_CACHE=1
          BUILDKIT_PROGRESS=plain
          MODEL_PATH=/app/models/saved/sentiment_model
          TOKENIZER_PATH=/app/models/saved/sentiment_tokenizer
        
    - name: Notify build status
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "✅ Docker image built and pushed successfully!"
          echo "Image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest"
          echo "Tag: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}"
        else
          echo "❌ Docker image build failed!"
        fi