name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests  # Explicitly install pytest and requests
        
    - name: Run unit tests
      run: |
        python -m pytest scripts/tests/ -v
        
    - name: Lint code
      run: |
        pip install flake8
        flake8 scripts/ --max-line-length=120 --exclude=__pycache__,venv

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployment/Dockerfile
        push: false
        tags: sentiment-analysis:latest
        load: true
        
    - name: Test Docker image
      run: |
        docker run --name test-container -d -p 8000:8000 sentiment-analysis:latest
        sleep 10
        docker ps
        docker logs test-container
        # Test the API endpoints
        curl -X GET http://localhost:8000/health
        curl -X POST http://localhost:8000/predict -H "Content-Type: application/json" -d '{"text": "This is good!"}' 