name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.11'
  DOCKER_IMAGE_NAME: sentiment-analysis
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest requests
        
    # - name: Run unit tests
    #   run: |
    #     python -m pytest scripts/tests/ -v
        
    - name: Lint code
      run: |
        pip install flake8
        # Only check for critical errors in test files
        flake8 scripts/tests/ --max-line-length=120 --exclude=__pycache__,venv --ignore=E302,E305,W293,W291,W292
        # Create a temporary .flake8 config file
        echo "[flake8]" > .flake8
        echo "ignore = E501,W503,W504" >> .flake8
        echo "exclude = scripts/tests/test_load_balancing.py" >> .flake8
        flake8 .

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: deployment/Dockerfile
        push: false
        tags: sentiment-analysis:latest
        load: true
        
    - name: Test Docker image
      run: |
        # Create necessary directories
        mkdir -p models/saved/sentiment_model
        mkdir -p models/saved/sentiment_tokenizer
        
        # Run container with test mode
        docker run --name test-container -d \
          -p 8000:8000 \
          -e TEST_MODE=true \
          -e SKIP_MODEL_LOAD=true \
          -e MODEL_PATH=/app/models/saved/sentiment_model \
          -e TOKENIZER_PATH=/app/models/saved/sentiment_tokenizer \
          sentiment-analysis:latest
        
        # Wait for container to start
        sleep 10
        
        # Check if container is running
        if ! docker ps | grep -q test-container; then
          echo "Container failed to start. Logs:"
          docker logs test-container
          exit 1
        fi
        
        # Check container logs
        echo "Container logs:"
        docker logs test-container
        
        # Test health endpoint
        echo "Testing health endpoint..."
        curl -X GET http://localhost:8000/health
        
        # Test sentiment analysis endpoint
        echo "Testing sentiment analysis endpoint..."
        curl -X POST http://localhost:8000/predict \
          -H "Content-Type: application/json" \
          -d '{"text": "This is a test sentence."}'
        
        # Clean up
        docker stop test-container
        docker rm test-container 